sonar.projectKey=Machine-Readable-Extension_mre
sonar.organization=machine-readable-extension

sonar.sources=mre
sonar.tests=mre/tests
sonar.exclusions=mre/tests/fixtures/**

sonar.python.coverage.reportPaths=coverage.xml
